trainer:
  DATA_FILE: "experiments/data/chembl29_predicting_target_P14416_P42336_target_1_vs_random_cpds.csv" #data location
  TRAIN_DATA_FILE: "experiments/data/data_splits/training.txt" #None #list of molecules to use as train set
  VALIDATION_DATA_FILE: "experiments/data/data_splits/validation.txt"
  TEST_DATA_FILE: "experiments/data/data_splits/test.txt"
  SAVE_FOLDER_DATA_SPLIT: null #"data/data_splits"
  SMILES_FIELD_NAME: "nonstereo_aromatic_smiles"
  LABEL_FIELD_NAME: "label"
  MODEL_SAVE_FOLDER: "protocol/models"
  HIDDEN_CHANNELS: 256
  BATCH_SIZE: 32
  EPOCHS: 100
  SEED: 42

explainer:
  MODEL: "protocol/models/model_best_model_2026_03_30-11_40_48.ckpt"
  DATA_FILE: "experiments/data/chembl29_predicting_target_P14416_P42336_target_1_vs_random_cpds.csv"
  TEST_DATA_FILE: "experiments/data/data_splits/test.txt" #list of molecules to use as test set (explained molecules should be in this set). If null, the test set will be the same as the data file but this could lead to the explanation of samples that were used to train the model.
  MOLECULES_TO_EXPLAIN: 20 # "protocol/molecules_to_explain.txt" #either an integer or a file with a list of molecules to explain
  TARGET_CLASS: 0
  SMILES_FIELD_NAME: "nonstereo_aromatic_smiles"
  LABEL_FIELD_NAME: "label"
  MINIMAL_SETS: True
  SAVE_FOLDER_PATH: "protocol/results/model_best_model_2026_03_30-11_40_48_parallelize_version"
  HIDDEN_CHANNELS: 256
  SAMPLING_STEPS: 100
  VISUALIZATION: True
  TOLERANCE: null
  SEED: 42
