trainer:
  DATA_PATH: "experiments/data/chembl29_predicting_target_P14416_P42336_target_1_vs_random_cpds.csv" #data location
  TRAIN_DATA_PATH: null #list of molecules to use as train set
  VALIDATION_DATA_PATH: null
  TEST_DATA_PATH: null
  SMILES_FIELD_NAME: "nonstereo_aromatic_smiles"
  LABEL_FIELD_NAME: "label"
  MODEL_SAVE_PATH: "protocol/models"
  HIDDEN_CHANNELS: 256
  BATCH_SIZE: 32
  EPOCHS: 100
  SEED: 42  

explainer:
  MODEL_PATH: "protocol/models/model_2022_09_06-17_29_37.ckpt"
  DATA_PATH: "experiments/data/chembl29_predicting_target_P14416_P42336_target_1_vs_random_cpds.csv"
  MOLECULES_TO_EXPLAIN: "protocol/molecules_to_explain.txt"
  TARGET_CLASS: 0
  SMILES_FIELD_NAME: "nonstereo_aromatic_smiles"
  LABEL_FIELD_NAME: "label"
  MINIMAL_SETS: True
  SAVE_PATH: "protocol/results"
  SAMPLING_STEPS: 100
  VISUALIZATION: True
  TOLERANCE: null
  SEED: 42
